site_name: Icicle
site_description: "Write asynchronous code using synchronous coding techniques in PHP"
site_author: "Aaron Piotrowski"
copyright: "&copy; Icicle contributors"
theme_dir: theme
strict: true
