site_name: 'Icicle documentation'
site_description: 'Write asynchronous code using synchronous coding techniques in PHP'
site_author: 'Aaron Piotrowski'
copyright: '&copy; Icicle contributors.'
theme_dir: theme
strict: true

markdown_extensions:
    - admonition
    - def_list

pages:
- Introduction: 'index.md'
- Documentation conventions: 'conventions.md'
- Installing: 'installing.md'
- Getting started: 'getting-started.md'
- Manual:
    - The Event Loop: 'manual/loop.md'
    - Promises: 'manual/promises.md'
    - Using promises: 'manual/using-promises.md'
    - Coroutines: 'manual/coroutines.md'
    - Writing coroutines: 'manual/writing-coroutines.md'
    - Concurrency: 'manual/concurrency.md'
    - Foreign asynchronous code: 'manual/foreign-async-code.md'
- API:
    - Loop: 'api/loop.md'
    - Promise: 'api/promise.md'
    - Coroutine: 'api/coroutine.md'
    - Stream: 'api/stream.md'
    - Socket: 'api/socket.md'
    - DNS: 'api/dns.md'
    - Concurrent: 'api/concurrent.md'

extra:
    version: v1.x
